### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by PhilipMourdjis** [bisect-pt/conan-mongo-cxx-driver#7]
Have been using this for a while but today am running into an issue:

`This api.bintray.com page can't be found
No web page was found for the web address: https://api.bintray.com/conan/bisect/bisect`

Any suggestions?

**Comment by promgamer** [comment]
Hi @PhilipMourdjis 

I've just checked everything and it seems to be working as usual. Maybe bintray was down for a while?

**Comment by PhilipMourdjis** [comment]
Turns out the issue was with how conan was installed. You have to install conan as root, and add remotes as a specific user. Installing it not as root means the conan command doesn't work, adding remotes as root means user accounts don't see them. Issue may be with installing conan in docker as I don't remember installing as root on my dev machine.

**Comment by promgamer** [comment]
Ok. Closing this issue as it is fixed!
